---
title: "Dental study summary"
format: 
  html:
    self-contained: true
    page-layout: full
    css: style.css
editor: source
editor_options: 
  chunk_output_type: console
execute:
  echo: false
  messages: false
  warning: false
---


```{r, setup}
library(tidyverse)
library(gtsummary)
library(lubridate)
library(networkD3)
library(bupaverse)
library(htmlwidgets)
library(widgetframe)

event_df <- readRDS('data/event_log_df.rds')
dental_df <- readRDS('data/all_iuc_dental_with_LSOA_df.rds')


# Age bins: 0-10, 11-20, 20-60, > 60 
# Follow all cases (index call to 24 hours and 7 days) 

table1_df <- dental_df %>%
  mutate(
    age = as.integer(index_age),
    age_bin = case_when(
      between(age, 0, 10) ~ "0-10",
      between(age, 11, 20) ~ "11-20",
      between(age, 21, 60) ~ "21-60",
      age > 60 ~ ">60",
      .default = NA_character_
    ),
    age_bin = factor(age_bin, levels = c("0-10", "11-20", "21-60", ">60")),
    sex = index_sex,
    IUC_service_referral = index_referral_group,
    ethnicity = fct_relevel(str_extract(index_ethnicity, "[^:]+"), 'White'),
    IMD_decile = factor(index_imd_decile, levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10")),
    dental_date = tbl_Dental_Data_NHBSA_start_date,
    #across(ends_with('_TEETH'), as.integer),
    EXEMPTION_REMISSION_FLAG = str_replace(EXEMPTION_REMISSION_FLAG, " -.*", "")
  ) %>%
  select(-age, -starts_with('index_'), -starts_with('tbl_'), -dental, index_call_date, index_call_ref) %>%
  group_by(index_call_ref) %>%
  mutate(
    time_to_dental = as.numeric(min(difftime(dental_date, index_call_date, units = 'days'), na.rm = T)),
  ) %>% ungroup() %>%
  mutate(
    `Time to dental contact (days)` = if_else(is.infinite(time_to_dental), NA_real_, time_to_dental),
    `Dental contact within 24 hours` = if_else(time_to_dental < 1, 'yes', 'no'),
    `Dental contact within 7 days` = if_else(time_to_dental < 7, 'yes', 'no')
  ) %>% select(
    -index_call_date, 
    -index_call_ref, 
    -dental_date, 
    -person_id,
    -TRT_LOCATION_POSTCODE,
    -TREATMENT_COMPLETED,
    -LSOA,
    -time_to_dental
  )

```

## Summary

```{r}
#| label: tbl-one
#| tbl-cap: Summary table

table1_df %>% 
  select(age_bin, sex, ethnicity, IMD_decile, IUC_service_referral, `Time to dental contact (days)`, `Dental contact within 24 hours`, `Dental contact within 7 days`, everything()) %>%
  tbl_summary(
    by = 'dental_contact',
    type = list(all_dichotomous() ~ "categorical"),
    sort = list(
      all_categorical() ~ "frequency",
      c("age_bin", "IMD_decile") ~ "alphanumeric"
    ),
    missing = "no"
  ) %>%
  bold_labels() %>%
  add_overall(last = T) %>%
  modify_spanning_header(c("stat_1", "stat_2") ~ "**Dental Contact**")


```


## First 5 healthcare contacts following index IUC/111 call with dental disposition

```{r}


s <- readRDS('data/sankey.rds')
frameWidget(s)

```


## Total contacts


```{r}

event_df %>% process_map(width = 1200, height = 1000)

```

### Median time to contact (days)

```{r}

event_df %>%
  process_map(performance(FUN=median, "days"), width = 1200, height = 1000)


```


### Total contacts and relative frequency

```{r}


event_df %>%
  process_map(type = frequency("relative_case"),
              sec = frequency("absolute"), width = 1200, height = 1000)

```


## IMD and distance/travel time to dental treatment centre

Distances in km and time in minutes

```{r}

imd_df <- readRDS('data/imd_df.rds')


imd_df %>%
  group_by(IMD) %>%
  summarise(
    n = n(),
    across(everything(), \(x) median(x, na.rm = T))
  ) %>% knitr::kable()



```


```{r}

imd_df %>%
  na.omit() %>%
  pivot_longer(-IMD) %>%
  ggplot(aes(x = IMD, y = value, fill = IMD)) +
  geom_boxplot(outlier.shape = NA) +
  ylim(c(0, 100)) +
  facet_wrap(~name, scales = "free_y") +
  theme_minimal()


```









